spring:
   application:
      name: user-service
server:
   port: 8083
logging:
   application-insights:
      instrumentation-key: 053ee39c-c27f-4563-b77c-57f96c20ed45      
   level:
      root: INFO
      org.epam: DEBUG   
azure:
   application-insights:
      instrumentation-key: 053ee39c-c27f-4563-b77c-57f96c20ed45      
   cosmos:
      uri: ${cosmouri}
      key: ${cosmokey}
      database: ${cosmodb}
      populateQueryMetrics: true
   keyvault:
      enabled: true
      uri: https://smkeyvaultt.vault.azure.net/