spring:
   application:
      name: user-service
server:
   port: 8083
logging:
   application-insights:
      instrumentation-key: 324cad6b-0410-485e-9418-76c1061a5ae5      
   level:
      root: INFO
      org.epam: DEBUG   
azure:
   application-insights:
      instrumentation-key: 324cad6b-0410-485e-9418-76c1061a5ae5      
   cosmos:
      uri: ${shoppingcosmouri}
      key: ${shoppingcosmokey}
      database: ${shoppingcosmodb}
      populateQueryMetrics: true
   keyvault:
      enabled: true
      uri: https://smkeyvault1.vault.azure.net/