spring:
   application:
      name: user-service
server:
   port: 8083
logging:
   application-insights:
      instrumentation-key: 053ee39c-c27f-4563-b77c-57f96c20ed45      
   level:
      root: INFO
      org.epam: DEBUG   
azure:
   application-insights:
      instrumentation-key: 053ee39c-c27f-4563-b77c-57f96c20ed45      
   cosmos:
      uri: ${cosmouri}
      key: ${cosmokey}
      database: ${cosmodb}
      populateQueryMetrics: true
   keyvault:
      client-id: 79035505-d142-4b59-a1e6-07c1ed7af0a3
      client-key: 1ecb5558-6d73-4454-9809-335e5775e57c
      enabled: true
      tenant-id: b41b72d0-4e9f-4c26-8a69-f949f367c91d
      uri: https://smkeyvault2.vault.azure.net/