apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    name: user-service-svc
    app: ctc-odp
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 31033
  selector:
    name: user-service-pod
    app: ctc-odp
  
